import json
import os
import re

# Root configuration file
CONFIG_PATH = "paynode-config.json"

def to_camel_case(snake_str):
    components = snake_str.split('_')
    return "".join(x.title() for x in components)

def sync_config():
    if not os.path.exists(CONFIG_PATH):
        print(f"Error: {CONFIG_PATH} not found.")
        return

    with open(CONFIG_PATH, "r") as f:
        config = json.load(f)

    min_amount = config["protocol"]["min_payment_amount"]
    base_usdc = config["networks"]["base"]["tokens"]["USDC"]
    sepolia_usdc = config["networks"]["baseSepolia"]["tokens"]["USDC"]
    
    base_rpcs = config["networks"]["base"]["rpcUrls"]
    sepolia_rpcs = config["networks"]["baseSepolia"]["rpcUrls"]
    
    error_codes = config.get("error_codes", {})

    # --- 1. Python SDK (paynode_sdk/constants.py & errors.py) ---
    python_constants_path = "packages/sdk-python/paynode_sdk/constants.py"
    if os.path.exists(python_constants_path):
        content = f'''# Generated by scripts/sync-config.py
PAYNODE_ROUTER_ADDRESS = "{config["networks"]["base"]["router"]}"
PAYNODE_ROUTER_ADDRESS_SANDBOX = "{config["networks"]["baseSepolia"]["router"]}"
BASE_USDC_ADDRESS = "{base_usdc}"
BASE_USDC_ADDRESS_SANDBOX = "{sepolia_usdc}"
BASE_USDC_DECIMALS = 6

PROTOCOL_TREASURY = "{config["protocol"]["treasury"]}"
PROTOCOL_FEE_BPS = {config["protocol"]["fee_bps"]}
MIN_PAYMENT_AMOUNT = {min_amount}

BASE_RPC_URLS = {json.dumps(base_rpcs)}
BASE_RPC_URLS_SANDBOX = {json.dumps(sepolia_rpcs)}

ACCEPTED_TOKENS = {{
    8453: ["{base_usdc}"],
    84532: ["{sepolia_usdc}"]
}}

PAYNODE_ROUTER_ABI = [
    {{
        "anonymous": False,
        "inputs": [
            {{"indexed": True, "name": "orderId", "type": "bytes32"}},
            {{"indexed": True, "name": "merchant", "type": "address"}},
            {{"indexed": True, "name": "payer", "type": "address"}},
            {{"indexed": False, "name": "token", "type": "address"}},
            {{"indexed": False, "name": "amount", "type": "uint256"}},
            {{"indexed": False, "name": "fee", "type": "uint256"}},
            {{"indexed": False, "name": "chainId", "type": "uint256"}}
        ],
        "name": "PaymentReceived",
        "type": "event"
    }}
]
'''
        with open(python_constants_path, "w") as f:
            f.write(content)
        print(f"✅ Synced: {python_constants_path}")

    python_errors_path = "packages/sdk-python/paynode_sdk/errors.py"
    if os.path.exists(python_errors_path):
        lines = ["from enum import Enum", "from typing import Any, Optional", "", "class ErrorCode(str, Enum):"]
        for code in error_codes:
            lines.append(f"    {code} = '{code}'")
        lines.extend(["", "class PayNodeException(Exception):", "    def __init__(self, message: str, code: ErrorCode, details: Optional[Any] = None):", "        super().__init__(message)", "        self.message = message", "        self.code = code", "        self.details = details"])
        with open(python_errors_path, "w") as f:
            f.write("\n".join(lines) + "\n")
        print(f"✅ Synced: {python_errors_path}")

    # --- 2. JS SDK (src/constants.ts & src/errors/index.ts) ---
    js_constants_path = "packages/sdk-js/src/constants.ts"
    if os.path.exists(js_constants_path):
        content = f'''/** Generated by scripts/sync-config.py */
export const PAYNODE_ROUTER_ADDRESS = "{config["networks"]["base"]["router"]}";
export const PAYNODE_ROUTER_ADDRESS_SANDBOX = "{config["networks"]["baseSepolia"]["router"]}";
export const BASE_USDC_ADDRESS = "{base_usdc}";
export const BASE_USDC_ADDRESS_SANDBOX = "{sepolia_usdc}";
export const PROTOCOL_TREASURY = "{config["protocol"]["treasury"]}";
export const PROTOCOL_FEE_BPS = {config["protocol"]["fee_bps"]};
export const MIN_PAYMENT_AMOUNT = BigInt({min_amount});

export const BASE_RPC_URLS = {json.dumps(base_rpcs)};
export const BASE_RPC_URLS_SANDBOX = {json.dumps(sepolia_rpcs)};

export const ACCEPTED_TOKENS: Record<number, string[]> = {{
    8453: ["{base_usdc}"],
    84532: ["{sepolia_usdc}"]
}};
'''
        with open(js_constants_path, "w") as f:
            f.write(content)
        print(f"✅ Synced: {js_constants_path}")

    js_errors_path = "packages/sdk-js/src/errors/index.ts"
    if os.path.exists(js_errors_path):
        lines = ["export enum ErrorCode {"]
        for code in error_codes:
            camel = to_camel_case(code)
            lines.append(f"  {camel} = \"{camel}\",")
        lines.extend(["}", "", "export class PayNodeException extends Error {", "  constructor(public message: string, public code: ErrorCode, public details?: any) {", "    super(message);", "    this.name = \"PayNodeException\";", "  }", "}"])
        with open(js_errors_path, "w") as f:
            f.write("\n".join(lines) + "\n")
        print(f"✅ Synced: {js_errors_path}")

    # --- 3. Web Portal (app/api/pom/config.ts) ---
    web_config_path = "apps/paynode-web/app/api/pom/config.ts"
    if os.path.exists(web_config_path):
        content = f'''/** Generated by scripts/sync-config.py */
export const BASE_MAINNET_CONFIG = {{
  chainId: {config["networks"]["base"]["chainId"]},
  rpcUrls: {json.dumps(base_rpcs)},
  routerAddress: "{config["networks"]["base"]["router"]}",
  usdcAddress: "{base_usdc}",
  treasury: "{config["protocol"]["treasury"]}"
}};

export const BASE_SEPOLIA_CONFIG = {{
  chainId: {config["networks"]["baseSepolia"]["chainId"]},
  rpcUrls: {json.dumps(sepolia_rpcs)},
  routerAddress: "{config["networks"]["baseSepolia"]["router"]}",
  usdcAddress: "{sepolia_usdc}",
  treasury: "{config["protocol"]["treasury"]}"
}};

export const getNetworkConfig = (isMainnet: boolean) => isMainnet ? BASE_MAINNET_CONFIG : BASE_SEPOLIA_CONFIG;
'''
        with open(web_config_path, "w") as f:
            f.write(content)
        print(f"✅ Synced: {web_config_path}")

    # --- 4. Smart Contracts (script/Config.s.sol) ---
    sol_config_path = "packages/contracts/script/Config.s.sol"
    if os.path.exists(os.path.dirname(sol_config_path)):
        def to_hex(addr): return addr if addr.startswith("0x") else f"0x{addr}"
        content = f'''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by scripts/sync-config.py
library Config {{
    address public constant ROUTER_MAINNET = {to_hex(config["networks"]["base"]["router"])};
    address public constant ROUTER_SEPOLIA = {to_hex(config["networks"]["baseSepolia"]["router"])};
    address public constant TREASURY = {to_hex(config["protocol"]["treasury"])};
    address public constant USDC_MAINNET = {to_hex(base_usdc)};
    address public constant USDC_SEPOLIA = {to_hex(sepolia_usdc)};
}}
'''
        with open(sol_config_path, "w") as f:
            f.write(content)
        print(f"✅ Synced: {sol_config_path}")

if __name__ == "__main__":
    sync_config()
