import json
import os

# Root configuration file
CONFIG_PATH = "paynode-config.json"

def sync_config():
    if not os.path.exists(CONFIG_PATH):
        print(f"Error: {CONFIG_PATH} not found.")
        return

    with open(CONFIG_PATH, "r") as f:
        config = json.load(f)

    min_amount = config["protocol"]["min_payment_amount"]
    base_usdc = config["networks"]["base"]["tokens"]["USDC"]
    sepolia_usdc = config["networks"]["baseSepolia"]["tokens"]["USDC"]

    # --- 1. Python SDK (paynode_sdk/constants.py) ---
    python_constants_path = "packages/sdk-python/paynode_sdk/constants.py"
    if os.path.exists(python_constants_path):
        content = f'''# Generated by scripts/sync-config.py
PAYNODE_ROUTER_ADDRESS = "{config["networks"]["base"]["router"]}"
PAYNODE_ROUTER_ADDRESS_SANDBOX = "{config["networks"]["baseSepolia"]["router"]}"
BASE_USDC_ADDRESS = "{base_usdc}"
BASE_USDC_ADDRESS_SANDBOX = "{sepolia_usdc}"
BASE_USDC_DECIMALS = 6

PROTOCOL_TREASURY = "{config["protocol"]["treasury"]}"
PROTOCOL_FEE_BPS = {config["protocol"]["fee_bps"]}
MIN_PAYMENT_AMOUNT = {min_amount}

ACCEPTED_TOKENS = {{
    8453: ["{base_usdc}"],
    84532: ["{sepolia_usdc}"]
}}
'''
        with open(python_constants_path, "w") as f:
            f.write(content)
        print(f"✅ Synced: {python_constants_path}")

    # --- 2. JS SDK (src/constants.ts) ---
    js_constants_path = "packages/sdk-js/src/constants.ts"
    if os.path.exists(js_constants_path):
        content = f'''/** Generated by scripts/sync-config.py */
export const PAYNODE_ROUTER_ADDRESS = "{config["networks"]["base"]["router"]}";
export const PAYNODE_ROUTER_ADDRESS_SANDBOX = "{config["networks"]["baseSepolia"]["router"]}";
export const BASE_USDC_ADDRESS = "{base_usdc}";
export const BASE_USDC_ADDRESS_SANDBOX = "{sepolia_usdc}";
export const PROTOCOL_TREASURY = "{config["protocol"]["treasury"]}";
export const PROTOCOL_FEE_BPS = {config["protocol"]["fee_bps"]};
export const MIN_PAYMENT_AMOUNT = BigInt({min_amount});

export const ACCEPTED_TOKENS: Record<number, string[]> = {{
    8453: ["{base_usdc}"],
    84532: ["{sepolia_usdc}"]
}};
'''
        with open(js_constants_path, "w") as f:
            f.write(content)
        print(f"✅ Synced: {js_constants_path}")

    # --- 3. Web Portal (app/api/pom/config.ts) ---
    web_config_path = "apps/paynode-web/app/api/pom/config.ts"
    if os.path.exists(web_config_path):
        content = f'''/** Generated by scripts/sync-config.py */
export const BASE_MAINNET_CONFIG = {{
  chainId: {config["networks"]["base"]["chainId"]},
  rpcUrl: "{config["networks"]["base"]["rpcUrl"]}",
  routerAddress: "{config["networks"]["base"]["router"]}",
  usdcAddress: "{base_usdc}",
  treasury: "{config["protocol"]["treasury"]}"
}};

export const BASE_SEPOLIA_CONFIG = {{
  chainId: {config["networks"]["baseSepolia"]["chainId"]},
  rpcUrl: "{config["networks"]["baseSepolia"]["rpcUrl"]}",
  routerAddress: "{config["networks"]["baseSepolia"]["router"]}",
  usdcAddress: "{sepolia_usdc}",
  treasury: "{config["protocol"]["treasury"]}"
}};

export const getNetworkConfig = (isMainnet: boolean) => isMainnet ? BASE_MAINNET_CONFIG : BASE_SEPOLIA_CONFIG;
'''
        with open(web_config_path, "w") as f:
            f.write(content)
        print(f"✅ Synced: {web_config_path}")

    # --- 4. Smart Contracts (script/Config.s.sol) ---
    sol_config_path = "packages/contracts/script/Config.s.sol"
    if os.path.exists(os.path.dirname(sol_config_path)):
        # Solidity requires 0x prefix for hex addresses
        def to_hex(addr): return addr if addr.startswith("0x") else f"0x{addr}"
        content = f'''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by scripts/sync-config.py
library Config {{
    address public constant ROUTER_MAINNET = {to_hex(config["networks"]["base"]["router"])};
    address public constant ROUTER_SEPOLIA = {to_hex(config["networks"]["baseSepolia"]["router"])};
    address public constant TREASURY = {to_hex(config["protocol"]["treasury"])};
    address public constant USDC_MAINNET = {to_hex(base_usdc)};
    address public constant USDC_SEPOLIA = {to_hex(sepolia_usdc)};
}}
'''
        with open(sol_config_path, "w") as f:
            f.write(content)
        print(f"✅ Synced: {sol_config_path}")

if __name__ == "__main__":
    sync_config()
